baseURL = ""
languageCode = "en-us"
title = "Another sysadmin blog"
theme = "basics"

[params]
author = "Sam Crauwels"
github = "Oddly"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4
