baseURL: "https://samcrauwels.info"
title: Technologic ramblings 
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Technology rambling 
    description: ""
    author: Sam 
    # author: ["Me", "You"] # multiple authors

    images: "<link or path of image for opengraph, twitter-cards>"

    ShowReadingTime: true
    ShowShareButtons: false
    comments: false
    defaultTheme: auto
    disableThemeToggle: false
    disableSpecial1stPost: false

    label:
        text: "Infrastructure adventures"
